# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

- name: Assert that required variables are provided
  ansible.builtin.assert:
    that:
      - variable.value
      - variable.value is defined
      - variable.value is not none
      - variable.value != None
      - variable.value != "None"
      - variable.value != ""
      - variable.value | length > 0
    fail_msg: "Verification for variables failed: missing required variable: {{ variable.key }}"
    success_msg: "Required variable: {{ variable.key }} provided"
    quiet: true
  loop: "{{ required_variables | dict2items }}"
  loop_control:
    loop_var: variable
    label: "{{ variable.key }}"
  when: required_variables is defined # and required_variables | length > 0

- name: Assert that multi tenancy and multiple AWS regions are not in use simultaneously
  ansible.builtin.assert:
    that:
      - aws_region is not defined or tenants is not defined or tenants | length == 0 or all_aws_regions | length == 1
      - az_location is not defined or tenants is not defined or tenants | length == 0 or az_all_locations | length == 1
    fail_msg: "Using multi tenancy and multiple AWS regions at the same time is not supported yet"
