# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

# For vBond
#
# 2 aws_network_interface
# 2 aws_network_interface_attachment
# 2 aws_eip
# 1 ec2 instance

- name: AMI Registration from EBS Snapshot
  amazon.aws.ec2_ami:
    name: "{{ aws_tag_creator }}-Validator"
    region: "{{ aws_region }}"
    state: present
    architecture: x86_64
    virtualization_type: hvm
    root_device_name: /dev/xvda
    device_mapping:
      - device_name: /dev/xvda
        snapshot_id: "{{ root_snapshot_id }}"
        delete_on_termination: true
        volume_type: gp2
    tags:
      Name: "{{ aws_tag_creator }}-Validator"
      Creator: "{{ aws_tag_creator }}"
  when: root_snapshot_id
  register: ami_result


# NICs
- name: Filter required subnets for instance creation. Set aws_mgmt_subnet and aws_transport_subnet facts
  ansible.builtin.set_fact:
    aws_mgmt_subnet: "{{ aws_subnets_config | selectattr('tags.VPN', 'equalto', '512') | list | first }}"
    aws_transport_subnet: "{{ aws_subnets_config | selectattr('tags.VPN', 'equalto', '0') | list | first }}"

- name: Create network interfaces for vBond
  amazon.aws.ec2_eni:
    subnet_id: "{{ subnet_item.id }}"
    description: Network interface for SD-WAN Controller
    security_groups: "{{ aws_security_group_config.group_id }}"
    region: "{{ aws_region }}"
    tags:
      Name: "nic-{{ subnet_item.tags.Name }}"
      Creator: "{{ aws_tag_creator }}"
      Machine: "{{ hostname }}"
      VPN: "{{ subnet_item.tags.VPN }}"
  register: network_interfaces_vbond
  loop: "{{ [aws_mgmt_subnet, aws_transport_subnet] }}"
  loop_control:
    loop_var: subnet_item
    label: "nic-{{ subnet_item.tags.Name }}"

- name: Set aws_network_interfaces fact with a list of interfaces for vBond
  ansible.builtin.set_fact:
    aws_network_interfaces: "{{ network_interfaces_vbond.results | map(attribute='interface') | list }}"

- name: Filter aws_network_interfaces for instance creation. Set aws_mgmt_nic and aws_transport_nic facts
  ansible.builtin.set_fact:
    aws_mgmt_nic: "{{ aws_network_interfaces | selectattr('tags.VPN', 'equalto', '512') | list | first }}"
    aws_transport_nic: "{{ aws_network_interfaces | selectattr('tags.VPN', 'equalto', '0') | list | first }}"


# EIPs
- name: Associate EIP with network interfaces
  amazon.aws.ec2_eip:
    device_id: "{{ interface_item.id }}"
    region: "{{ aws_region }}"
    in_vpc: true
    state: present
    reuse_existing_ip_allowed: true
    tags:
      Name: "eip-for-{{ interface_item.tags.Name }}"
      Creator: "{{ aws_tag_creator }}"
      Machine: "{{ hostname }}"
      VPN: "{{ interface_item.tags.VPN }}"
  loop: "{{ [aws_mgmt_nic, aws_transport_nic] }}"  # We do loop starting with mgmt nic, so we know results[0] is mgmt ip
  loop_control:
    loop_var: interface_item
    label: "eip-for-{{ interface_item.tags.Name }}"
  register: eip_vbond
  retries: 3
  delay: 3
  until: eip_vbond is succeeded

# vbond_mgmt_private_ip
- name: Set vbond_mgmt_private_ip fact
  ansible.builtin.set_fact:
    vbond_mgmt_private_ip: "{{ aws_mgmt_nic.private_ip_address }}"
    vbond_transport_private_ip: "{{ aws_transport_nic.private_ip_address }}"
    vbond_mgmt_public_ip: "{{ eip_vbond.results[0].public_ip }}"
    vbond_transport_public_ip: "{{ eip_vbond.results[1].public_ip }}"


# template cloud init with proper ip assigned to EiP
# cloud-init
- name: Set path for bootstrap configuration
  ansible.builtin.set_fact:
    generated_userdata_vbond: "{{ userdata_vbond_path }}-{{ hostname }}"
  changed_when: true

- name: Template userdata file for vBond
  ansible.builtin.template:
    src: ./userdata_vbond.j2
    dest: "{{ generated_userdata_vbond }}"
    mode: "0644"


# vBond
- name: Launch vBond
  amazon.aws.ec2_instance:
    count: 1
    instance_type: "{{ aws_vbond_instance_type }}"
    image:
      id: "{{ ami_result.image_id if root_snapshot_id else aws_vbond_ami_id }}"
    state: present
    vpc_subnet_id: "{{ aws_mgmt_subnet.id }}"
    region: "{{ aws_region }}"
    key_name: "{{ aws_key_name | default('') | bool | ternary(aws_key_name, omit) }}"
    network:
      assign_public_ip: false
      interfaces:
        - id: "{{ aws_mgmt_nic.id }}"
          device_index: 0
          description: "{{ aws_mgmt_nic.tags.Name }}"
        - id: "{{ aws_transport_nic.id }}"
          device_index: 1
          description: "{{ aws_transport_nic.tags.Name }}"
    name: "{{ hostname }}"
    tags:
      Name: "{{ hostname }}"
      Creator: "{{ aws_tag_creator }}"
    user_data: "{{ lookup('file', generated_userdata_vbond) }}"
    volumes:
      - device_name: /dev/xvda
        ebs:
          volume_size: 23
          delete_on_termination: true
  register: ec2_vbond

- name: Deregister/Delete AMI (keep associated snapshots)
  amazon.aws.ec2_ami:
    image_id: "{{ ami_result.image_id }}"
    delete_snapshot: false
    state: absent
    region: "{{ aws_region }}"
  when: root_snapshot_id

- name: Store vBond instance details for deployment_results
  ansible.builtin.set_fact:
    instance:
      hostname: "{{ hostname }}"
      system_ip: "{{ system_ip }}"
      admin_username: "{{ admin_username }}"
      admin_password: "{{ admin_password }}"
      mgmt_public_ip: "{{ eip_vbond.results[0].public_ip }}"
      transport_public_ip: "{{ eip_vbond.results[1].public_ip }}"
      mgmt_public_ipv6: "{{ _created_mgmt_nic.ipv6_addresses[0].ipv6_address }}"
      transport_public_ipv6: "{{ _created_transport_nic.ipv6_addresses[0].ipv6_address }}"
  changed_when: true
  notify: Show deployment_facts
  register: _vbond_facts
  retries: 3
  delay: 5
  until: _vbond_facts is succeeded
  vars:
    _created_mgmt_nic: "{{ ec2_vbond.instances[0].network_interfaces | json_query('[?subnet_id==`'~aws_mgmt_subnet.id~'`]') | first }}"
    _created_transport_nic: "{{ ec2_vbond.instances[0].network_interfaces | json_query('[?subnet_id==`'~aws_transport_subnet.id~'`]') | first }}"

- name: Update deployment facts - vBond - that will be consumed by vManage-client in Ansible
  ansible.builtin.set_fact:
    deployment_facts:
      vbond_instances: "{{ deployment_facts.vbond_instances + [instance] }}"
      vmanage_instances: "{{ deployment_facts.vmanage_instances }}"
      vsmart_instances: "{{ deployment_facts.vsmart_instances }}"

- name: Copy resources information to log file
  ansible.builtin.blockinfile:
    create: true
    state: present
    mode: "0644"
    insertafter: EOF
    dest: "{{ aws_deployed_controllers_data }}"
    marker: "\n--------------    ec2 vBond   --------------\n"
    content: "{{ ec2_vbond | to_nice_yaml }}"

- name: Allow traffic outside VPC for vBond IP addresses
  amazon.aws.ec2_security_group:
    name: "{{ aws_security_group_config.group_name }}"
    description: "Security Group for SD-WAN instances"
    vpc_id: "{{ aws_vpc_config.id }}"
    region: "{{ aws_region }}"
    purge_rules: false
    purge_tags: false
    purge_rules_egress: false
    rules: "{{ sg_rules_vbond }}"
    rules_egress: "{{ sg_rules_vbond if aws_sg_block_egress else [] }}"
  vars:
    sg_rules_vbond:
      - proto: all
        cidr_ip: "{{ eip_vbond.results[0].public_ip }}/32"
        rule_desc: "{{ hostname }} - mgmt (VPN 512)"
      - proto: all
        cidr_ip: "{{ eip_vbond.results[1].public_ip }}/32"
        rule_desc: "{{ hostname }} - transport (VPN 0)"
      - proto: all
        cidr_ipv6: "{{ instance.mgmt_public_ipv6 }}/128"
        rule_desc: "{{ hostname }} - mgmt IPv6 (VPN 512)"
      - proto: all
        cidr_ipv6: "{{ instance.transport_public_ipv6 }}/128"
        rule_desc: "{{ hostname }} - transport IPv6 (VPN 0)"
  register: allow_traffic
  retries: 3
  delay: 3
  until: allow_traffic is succeeded

- name: Create record in internal DNS zone
  amazon.aws.route53:
    state: present
    hosted_zone_id: "{{ aws_hosted_zone.id }}"
    record: "{{ vbond_transport_hostname }}"
    type: "{{ item.type }}"
    ttl: 300
    value: "{{ item.value }}"
    wait: true
  loop:
    - type: A
      value: "{{ instance.transport_public_ip }}"
    - type: AAAA
      value: "{{ instance.transport_public_ipv6 }}"
